platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
    tag: final

inputs:
  - name: pipeline_repo
outputs:
  - name: email
params:
  OPSMAN_CLIENT_ID:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  ENV:

run:
  path: pipeline_repo/ci/assets/template/concourse/pipelines/tasks/apply-updates.sh
