product-name: credhub-service-broker
product-properties:
  .properties.allow_paid_service_plans:
    value: false
  .properties.apply_open_security_group:
    value: false
  .properties.credhub_broker_enable_global_access_to_plans:
    value: true
  .properties.org:
    value: credhub-service-broker-org
  .properties.space:
    value: credhub-service-broker-space
network-properties:
  network:
    name: services
  other_availability_zones:
  - name: Availability Sets
  singleton_availability_zone:
    name: Availability Sets
resource-config:
  delete-all:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
    max_in_flight: 1
  deploy-all:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
    max_in_flight: 1
errand-config:
  delete-all:
    pre-delete-state: true
  deploy-all:
    post-deploy-state: true
