properties-configuration:
  director_configuration:
    ntp_servers_string: {{.ntp_server}}
    director_hostname: {{.director_hostname}}
    post_deploy_enabled: true
    resurrector_enabled: true
  iaas_configuration:
    subscription_id: {{.subscription_id}}
    tenant_id: {{.tenant_id}}
    client_id: {{.client_id}}
    client_secret: {{.client_secret}}
    resource_group_name: {{.pcf_resource_group_name}}
    bosh_storage_account_name: {{.bosh_root_storage_account}}
    ssh_public_key: {{.ops_manager_ssh_public_key}}
    ssh_private_key: {{toJson .ops_manager_ssh_private_key}}
    deployments_storage_account_name: '*zpcfdep*'
    cloud_storage_type: storage_accounts
    availability_mode: availability_sets
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
    trusted_certificates: |
{{indent 10 .ssl_cert}}
network-assignment:
  network:
    name: {{.infrastructure_subnet_name}}
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: {{.infrastructure_subnet_name}}
    subnets:
    {{range $i, $a := .infrastructure_subnet_cidrs}}
    - cidr: {{index $.infrastructure_subnet_cidrs $i}}
      dns: {{$.dns_server}}
      gateway: {{$.infrastructure_subnet_gateway}}
      iaas_identifier: {{$.pcf_spoke_resource_group}}/{{$.network_name}}/{{$.infrastructure_subnet_name}}
      reserved_ip_ranges: {{cidrhost (index $.infrastructure_subnet_cidrs $i) 0}}-{{cidrhost (index $.infrastructure_subnet_cidrs $i) 5}},{{cidrhost (index $.infrastructure_subnet_cidrs $i) 7}}-{{cidrhost (index $.infrastructure_subnet_cidrs $i) 12}}
    {{end}}
{{if  index . "pas_subnet_cidrs"}}
  - name: {{.pas_subnet_name}}
    subnets:
    {{range $i, $a := .pas_subnet_cidrs}}
    - cidr: {{index $.pas_subnet_cidrs $i}}
      dns: {{$.dns_server}}
      gateway: {{$.pas_subnet_gateway}}
      iaas_identifier: {{$.pcf_spoke_resource_group}}/{{$.network_name}}/{{$.pas_subnet_name}}
      reserved_ip_ranges: {{cidrhost (index $.pas_subnet_cidrs $i) 0}}-{{cidrhost (index $.pas_subnet_cidrs $i) 10}}
    {{end}}
{{end}}
{{if  index . "pks_subnet_cidrs"}}
  - name: {{.pks_subnet_name}}
    subnets:
    {{range $i, $a := .pks_subnet_cidrs}}
    - cidr: {{index $.pks_subnet_cidrs $i}}
      dns: {{$.dns_server}}
      gateway: {{$.pks_subnet_gateway}}
      iaas_identifier: {{$.pcf_spoke_resource_group}}/{{$.network_name}}/{{$.pks_subnet_name}}
      reserved_ip_ranges: {{cidrhost (index $.pks_subnet_cidrs $i) 0}}-{{cidrhost (index $.pks_subnet_cidrs $i) 5}}
    {{end}}
{{end}}
{{if index . "services_subnet_cidrs"}}
  - name: {{.services_subnet_name}}
    subnets:
    {{range $i, $a := .services_subnet_cidrs}}
    - cidr: {{index $.services_subnet_cidrs $i}}
      dns: {{$.dns_server}}
      gateway: {{$.services_subnet_gateway}}
      iaas_identifier: {{$.pcf_spoke_resource_group}}/{{$.network_name}}/{{$.services_subnet_name}}
      reserved_ip_ranges: {{cidrhost (index $.services_subnet_cidrs $i) 0}}-{{cidrhost (index $.services_subnet_cidrs $i) 5}}
    {{end}}
{{end}}
resource-configuration:
  compilation:
    instance_type:
      id: automatic
