---
name: gogs

instance_groups:
- name: gogs
  azs:
    - Availability Sets
  instances: 1
  vm_type: Standard_F1s
  stemcell: default
  persistent_disk: 1024
  networks: [{name: services}]
  jobs:
  - name: postgres
    release: gogs
  - name: gogs
    release: gogs
  - name: gogs-admin
    release: gogs
- name: sanity-test
  azs:
    - Availability Sets
  instances: 1
  lifecycle: errand
  vm_type: Standard_F1s
  stemcell: default
  networks: [{name: services}]
  jobs:
  - name: sanity_test
    release: gogs

properties:
  gogs:
    admin: gogs
    domain: git.sys.REPLACE_ME_DNS
    port: 443
    protocol: https
    password: "REPLACE_ME"
    tls_cert: ((gogs-tls.certificate))
    tls_key: ((gogs-tls.private_key))
    secret_key: ((gogs-secret-key))
  databases:
    roles:
      - tag: gogs
        name: gogs
        password: ((postgres-password))
    databases:
      - tag: gogs
        name: gogsdb
        citext: true

variables:
- name: postgres-password
  type: password
- name: gogs-secret-key
  type: password
- name: gogs-ca
  type: certificate
  options:
    is_ca: true
    common_name: gogsCA
- name: gogs-tls
  type: certificate
  options:
    ca: gogs-ca
    common_name: gogs
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - "*.gogs.default.gogs.bosh"

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  os: ubuntu-xenial
  version: "250.79"

releases:
- name: gogs
  version: 5.5.1