product-name: harbor-container-registry
product-properties:
  .properties.admin_password:
    value:
      secret: {{.admin_password}}
  .properties.admin_password_for_smoketest:
    value:
      secret: {{.admin_password_for_smoketest}}
  .properties.server_cert_key:
    value:
      cert_pem: |
{{indent 10 .ssl_cert}}
      private_key_pem:  |
{{indent 10 .ssl_private_key}}
  .properties.auth_mode:
    selected_option: ldap_auth
    value: ldap_auth
  .properties.clair_updater_interval:
    value: 0
  .properties.customize_container_network:
    selected_option: default
    value: default
  .properties.hostname:
    value: {{.hostname}}
  .properties.no_proxy:
    value: 127.0.0.1,localhost,ui,registry
  .properties.registry_storage:
    selected_option: filesystem
    value: filesystem
  .properties.with_clair:
    value: true
  .properties.with_notary:
    value: true
network-properties:
  network:
    name: {{.services_subnet_name}}
  other_availability_zones:
  - name: Availability Sets
  singleton_availability_zone:
    name: Availability Sets
resource-config:
  harbor-app:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
    elb_names:
    - {{.harbor_lb_name}}
  smoke-testing:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: false
errand-config:
  smoke-testing:
    post-deploy-state: false
  uaa-deregistration:
    pre-delete-state: false