product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: |
{{indent 10 .ssl_cert}}
      private_key_pem: |
{{indent 10 .ssl_private_key}}
  .properties.cloud_provider:
    selected_option: azure
    value: Azure
  .properties.telemetry_installation_purpose_selector:
    selected_option: demo_or_poc
    value: demo_or_poc
  .properties.cloud_provider.azure.azure_cloud_name:
    value: AzurePublicCloud
  .properties.cloud_provider.azure.azure_master_managed_identity:
    value: pks-master
  .properties.cloud_provider.azure.azure_worker_managed_identity:
    value: pks-worker
  .properties.cloud_provider.azure.default_security_group:
    value: {{.default_security_group}}
  .properties.cloud_provider.azure.location:
    value: {{.location}}
  .properties.cloud_provider.azure.primary_availability_set:
    value: {{.primary_availability_set}}
  .properties.cloud_provider.azure.resource_group_name:
    value: {{.pcf_resource_group_name}}
  .properties.cloud_provider.azure.subscription_id:
    value: {{.subscription_id}}
  .properties.cloud_provider.azure.tenant_id:
    value: {{.tenant_id}}
  .properties.cloud_provider.azure.vnet_name:
    value: {{.vnet_name}}
  .properties.cloud_provider.azure.vnet_resource_group_name:
    value: {{.pcf_spoke_resource_group}}
  .properties.network_selector:
    selected_option: flannel
    value: flannel
  .properties.network_selector.flannel.pod_network_cidr:
    value: 10.200.0.0/16
  .properties.network_selector.flannel.service_cluster_cidr:
    value: 10.100.200.0/24
  .properties.pks-vrli:
    selected_option: disabled
    value: disabled
  .properties.pks_api_hostname:
    value: {{.pks_api_hostname}}
  .properties.plan1_selector:
    selected_option: active
    value: Plan Active
  .properties.plan1_selector.active.allow_privileged_containers:
    value: false
  .properties.plan1_selector.active.description:
    value: 'Example: This plan will configure a lightweight kubernetes cluster. Not
      recommended for production workloads.'
  .properties.plan1_selector.active.master_az_placement:
    value:
    - Availability Sets
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.max_worker_instances:
    value: 50
  .properties.plan1_selector.active.name:
    value: small
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - Availability Sets
  .properties.plan1_selector.active.worker_instances:
    value: 3
  .properties.plan2_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan3_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan4_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.plan10_selector:
    selected_option: inactive
    value: Plan Inactive
  .properties.proxy_selector:
    selected_option: disabled
    value: Disabled
  .properties.telemetry_selector:
    value: disabled
  .properties.syslog_selector:
    selected_option: disabled
    value: disabled
  .properties.telemetry_selector.enabled.billing_polling_interval:
    value: 60
  .properties.telemetry_selector.enabled.environment_provider:
    value: none
  .properties.telemetry_selector.enabled.telemetry_polling_interval:
    value: 600
  .properties.telemetry_selector.enabled.telemetry_url:
    value: https://vcsa.vmware.com/ph
  .properties.uaa:
    selected_option: ldap
    value: ldap
  .properties.uaa.ldap.credentials:
    value:
      identity: {{.ldap_user}}
      password: "{{.ldap_pass}}"
  .properties.uaa.ldap.external_groups_whitelist:
    value: '*'
  .properties.uaa.ldap.group_search_base:
    value: {{.ldap_group_search_base}}
  .properties.uaa.ldap.group_search_filter:
    value: member={0}
  .properties.uaa.ldap.ldap_referrals:
    value: follow
  .properties.uaa.ldap.mail_attribute_name:
    value: mail
  .properties.uaa.ldap.search_base:
    value: {{.ldap_user_search_base}}
  .properties.uaa.ldap.search_filter:
    value: userPrincipalName={0}
  .properties.uaa.ldap.url:
    value: {{.ldap_urls}}
  .properties.oidc_selector:
    selected_option: disabled
    value: disabled
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.wavefront:
    selected_option: disabled
    value: disabled
  .properties.worker_max_in_flight:
    value: 1
network-properties:
  network:
    name: {{.pks_infrastructure_network}}
  other_availability_zones:
  - name: Availability Sets
  service_network:
    name: {{.pcf_pks_network}}
  singleton_availability_zone:
    name: Availability Sets
resource-config:
  pivotal-container-service:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
    elb_names:
    - {{.pks_lb_name}}
errand-config:
  delete-all-clusters:
    pre-delete-state: true
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: false
  upgrade-all-service-instances:
    post-deploy-state: true
  wavefront-alert-creation:
    post-deploy-state: false
  wavefront-alert-deletion:
    pre-delete-state: false