product-name: p_spring-cloud-services
product-properties:
  .properties.allow_paid_service_plans:
    value: false
  .properties.apply_open_security_group:
    value: false
  .properties.config_server_access:
    value: global
  .properties.java_buildpack:
    value: java_buildpack_offline
  .properties.org:
    value: p-spring-cloud-services
  .properties.space:
    value: p-spring-cloud-services
  .properties.status_change_timeout_minutes:
    value: 30
network-properties:
  network:
    name: services
  other_availability_zones:
  - name: Availability Sets
  singleton_availability_zone:
    name: Availability Sets
resource-config:
  spring-cloud-services:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
    max_in_flight: 1
errand-config:
  destroy-brokers:
    pre-delete-state: true
  register-brokers:
    post-deploy-state: true